# Generated by Django 3.2 on 2021-04-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_comment_comment_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
