# Generated by Django 3.2 on 2021-04-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
    ]
