# Generated by Django 3.2 on 2021-04-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_rename_body_comment_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='comment',
        ),
    ]
